const mongoose = require('mongoose');
require('dotenv').config();

const Product = require('./models/Product');
const Cart = require('./models/Cart');


const products = [
  // ===== SHIRTS =====
  {
    title: 'Amazon Essentials Men\'s Regular-Fit Short-Sleeve Oxford Shirt',
    price: 24.90,
    originalPrice: 29.90,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=750&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=750&fit=crop',
    ],
    description: 'A classic button-down shirt featuring a comfortable regular fit. Made with lightweight, breathable cotton for everyday wear. Features a single chest pocket and a button-down collar. Machine wash cold, tumble dry low.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Light Blue', 'White', 'Navy'],
    stock: 120,
    featured: true,
    trending: true,
    reviews: [
      { userName: 'James R.', rating: 5, comment: 'Great fit and excellent value for money.' },
      { userName: 'Michael T.', rating: 4, comment: 'Slightly longer than expected but overall good.' },
    ],
    averageRating: 4.5,
  },
  {
    title: 'Van Heusen Men\'s Dress Shirt Regular Fit Poplin Solid',
    price: 34.99,
    originalPrice: 45.00,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&h=750&fit=crop',
    description: 'Wrinkle-free poplin dress shirt designed for the modern professional. Regular fit offers a generous cut through the shoulders, chest and waist. Point collar and adjustable cuffs.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black'],
    stock: 85,
    featured: true,
    trending: false,
    reviews: [{ userName: 'Robert W.', rating: 5, comment: 'Truly wrinkle free straight out of the dryer.' }],
    averageRating: 5.0,
  },
  {
    title: 'Tommy Hilfiger Men\'s Custom Fit Solid Polo Shirt',
    price: 49.50,
    originalPrice: 69.50,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&h=750&fit=crop',
    description: 'Classic Tommy Hilfiger polo featuring the iconic flag logo on the left chest. 100% Cotton pique fabric for maximum comfort and breathability. Custom fit provides a modern, tailored silhouette.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Red', 'White'],
    stock: 60,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Alex H.', rating: 4, comment: 'Classic look, fits well.' }],
    averageRating: 4.0,
  },
  {
    title: 'Levi\'s Men\'s Classic Western Denim Shirt',
    price: 59.99,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=600&h=750&fit=crop',
    description: 'The original denim shirt since 1955. Features classic western snap pockets, front snap placket, and pointed yokes. 100% cotton non-stretch denim.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Medium Wash', 'Dark Wash'],
    stock: 40,
    featured: true,
    trending: true,
    reviews: [],
    averageRating: 0,
  },
  {
    title: 'Goodthreads Men\'s Slim-Fit Long-Sleeve Linen Shirt',
    price: 30.90,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=750&fit=crop',
    description: 'A breathable linen blend perfect for summer days. Slim fit conforms closely to the body. Features a spread collar and round hem.',
    sizes: ['S', 'M', 'L'],
    colors: ['Olive', 'White', 'Beige'],
    stock: 30,
    featured: false,
    trending: false,
    reviews: [{ userName: 'David K.', rating: 4, comment: 'Nice and cool for summer, wrinkles easily though.' }],
    averageRating: 4.0,
  },

  // ===== T-SHIRTS =====
  {
    title: 'Hanes Men\'s Beefy-T Crewneck Short-Sleeve T-Shirt',
    price: 12.00,
    originalPrice: 18.00,
    category: 'T-Shirts',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=750&fit=crop',
    description: 'Heavyweight cotton jersey feels soft and thick. Lay-flat collar keeps its shape wash after wash. Durable double-needle stitching.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Heather Grey'],
    stock: 200,
    featured: true,
    trending: true,
    reviews: [
      { userName: 'Sam K.', rating: 5, comment: 'The only t-shirts I buy.' },
      { userName: 'Tom L.', rating: 5, comment: 'Thick and durable.' }
    ],
    averageRating: 5.0,
  },
  {
    title: 'Under Armour Men\'s Tech 2.0 Short-Sleeve T-Shirt',
    price: 25.00,
    category: 'T-Shirts',
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=750&fit=crop',
    description: 'UA Tech fabric is quick-drying, ultra-soft & has a more natural feel. Material wicks sweat & dries really fast. New, streamlined fit & shaped hem.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Carbon Heather', 'Royal Blue', 'Red'],
    stock: 150,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Mike', rating: 4, comment: 'Great for workouts.' }],
    averageRating: 4.0,
  },
  {
    title: 'Champion Men\'s Classic Graphic Tee',
    price: 20.00,
    originalPrice: 25.00,
    category: 'T-Shirts',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=750&fit=crop',
    description: 'Ring-spun cotton blend for a softer feel. Athletic fit for comfort. Screen-printed Champion script logo on center chest.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Navy'],
    stock: 80,
    featured: false,
    trending: false,
    reviews: [],
    averageRating: 0,
  },

  // ===== PANTS =====
  {
    title: 'Dockers Men\'s Classic Fit Easy Khaki Pants',
    price: 39.99,
    originalPrice: 60.00,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=750&fit=crop',
    description: 'Classic fit khaki pants featuring stretch for performance and comfort. No Wrinkle technology gives you a freshly pressed look around the clock.',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Khaki', 'Navy', 'Black'],
    stock: 110,
    featured: true,
    trending: true,
    reviews: [
      { userName: 'Steve W.', rating: 4, comment: 'Good quality work pants.' },
      { userName: 'Bill G.', rating: 5, comment: 'Very comfortable waistband.' }
    ],
    averageRating: 4.5,
  },
  {
    title: 'Levi\'s Men\'s 501 Original Fit Jeans',
    price: 69.50,
    originalPrice: 79.50,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=750&fit=crop',
    description: 'The original blue jean since 1873. Features a straight fit with a signature button fly. 100% cotton, no stretch.',
    sizes: ['30', '32', '34', '36'],
    colors: ['Dark Stonewash', 'Medium Stonewash', 'Black'],
    stock: 95,
    featured: true,
    trending: true,
    reviews: [{ userName: 'Mark H.', rating: 5, comment: 'Classic Levis, you can\'t go wrong.' }],
    averageRating: 5.0,
  },
  {
    title: 'Southpole Men\'s Active Basic Jogger Fleece Pants',
    price: 18.99,
    originalPrice: 24.99,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=750&fit=crop',
    description: 'Comfortable fleece joggers featuring an elastic waistband with adjustable drawstring. Ribbed ankle cuffs and side pockets.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Heather Grey', 'Black', 'Navy'],
    stock: 140,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Jake S.', rating: 4, comment: 'Very soft, great for lounging.' }],
    averageRating: 4.0,
  },
  {
    title: 'Wrangler Authentics Men\'s Classic Cargo Pant',
    price: 29.99,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=600&h=750&fit=crop',
    description: 'Relaxed fit cargo pants made from 100% cotton twill. Features 6 pockets including 2 side cargo pockets with hook and loop closures.',
    sizes: ['32', '34', '36', '38'],
    colors: ['British Khaki', 'Olive', 'Anthracite'],
    stock: 75,
    featured: false,
    trending: false,
    reviews: [],
    averageRating: 0,
  },
  {
    title: 'Calvin Klein Men\'s Slim Fit Dress Pants',
    price: 89.00,
    originalPrice: 110.00,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop',
    description: 'Modern slim fit dress pants tailored from a premium stretch wool blend. Flat front design with a subtle tapered leg. Perfect for the office or special events.',
    sizes: ['30', '32', '34', '36'],
    colors: ['Charcoal', 'Navy', 'Black'],
    stock: 40,
    featured: true,
    trending: false,
    reviews: [{ userName: 'Eric T.', rating: 5, comment: 'Looks incredibly sharp.' }],
    averageRating: 5.0,
  },

  // ===== SHOES =====
  {
    title: 'Cole Haan Men\'s Grand Crosscourt Sneaker',
    price: 89.95,
    originalPrice: 150.00,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=750&fit=crop',
    description: 'Classic minimalist sneaker featuring genuine leather uppers. Grand.OS technology provides lightweight cushioning and flexibility.',
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['White', 'Cognac'],
    stock: 55,
    featured: true,
    trending: true,
    reviews: [
      { userName: 'Daniel K.', rating: 5, comment: 'Very comfortable and stylish.' },
      { userName: 'Brian C.', rating: 4, comment: 'Runs a bit narrow, but breaks in nicely.' }
    ],
    averageRating: 4.5,
  },
  {
    title: 'Clarks Men\'s Bushacre 2 Chukka Boot',
    price: 60.00,
    originalPrice: 100.00,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600&h=750&fit=crop',
    description: 'A rugged yet refined chukka boot made from genuine suede or beeswax leather. Features a synthetic sole designed to mimic the classic crepe sole.',
    sizes: ['8', '9', '10', '11', '12', '13'],
    colors: ['Beeswax Leather', 'Dark Brown Suede'],
    stock: 80,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Will J.', rating: 4, comment: 'Great boots for the price.' }],
    averageRating: 4.0,
  },
  {
    title: 'Sperry Men\'s Authentic Original 2-Eye Boat Shoe',
    price: 95.00,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&h=750&fit=crop',
    description: 'The iconic boat shoe featuring full-grain leather uppers and genuine hand-sewn moccasin construction. Non-marking rubber outsole with Wave-Siping for wet/dry traction.',
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['Sahara', 'Amaretto', 'Navy'],
    stock: 65,
    featured: false,
    trending: false,
    reviews: [{ userName: 'Sam A.', rating: 5, comment: 'A summer essential.' }],
    averageRating: 5.0,
  },
  {
    title: 'ASICS Men\'s Gel-Venture 8 Running Shoes',
    price: 55.00,
    originalPrice: 70.00,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=750&fit=crop',
    description: 'Durable trail running shoe featuring GEL Technology cushioning for excellent shock absorption. Re-engineered outsole lugs for better off-road traction.',
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['Black/Sheet Rock', 'Graphite Grey/Directoire Blue'],
    stock: 120,
    featured: true,
    trending: true,
    reviews: [{ userName: 'Chris P.', rating: 4, comment: 'Very supportive for long walks.' }],
    averageRating: 4.0,
  },
  {
    title: 'Florsheim Men\'s Midtown Wingtip Oxford',
    price: 115.00,
    originalPrice: 125.00,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600&h=750&fit=crop',
    description: 'Classic wingtip oxford crafted from full-grain leather. Features a removable Ortholite footbed and a flexible rubber sole.',
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['Cognac', 'Black'],
    stock: 35,
    featured: false,
    trending: false,
    reviews: [],
    averageRating: 0,
  },

  // ===== ACCESSORIES =====
  {
    title: 'Timberland Men\'s Classic Leather Belt',
    price: 19.99,
    originalPrice: 25.00,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=750&fit=crop',
    description: '100% genuine leather belt perfect for jeans or khakis. Features a classic single-prong buckle and an embossed Timberland logo.',
    sizes: ['32', '34', '36', '38', '40'],
    colors: ['Brown', 'Black'],
    stock: 150,
    featured: true,
    trending: true,
    reviews: [{ userName: 'Kevin D.', rating: 4, comment: 'Solid daily belt.' }],
    averageRating: 4.0,
  },
  {
    title: 'Citizen Men\'s Eco-Drive Chronograph Stainless Steel Watch',
    price: 260.00,
    originalPrice: 350.00,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&h=750&fit=crop',
    description: 'Eco-Drive technology powered by light—never needs a battery. Stainless steel case and bracelet. Features a 1/5 second chronograph measuring up to 60 minutes, 12/24 hour time, and date.',
    sizes: ['One Size'],
    colors: ['Silver/Blue Dial'],
    stock: 25,
    featured: true,
    trending: true,
    reviews: [
      { userName: 'Nathan R.', rating: 5, comment: 'Beautiful dial and runs perfectly.' },
      { userName: 'Peter G.', rating: 5, comment: 'Amazing value.' }
    ],
    averageRating: 5.0,
  },
  {
    title: 'Carhartt Men\'s Knit Cuffed Beanie',
    price: 19.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=750&fit=crop',
    description: 'The classic Carhartt beanie. 100% acrylic rib-knit fabric for warmth and stretch. Carhartt label sewn on front.',
    sizes: ['One Size'],
    colors: ['Carhartt Brown', 'Black', 'Heather Grey'],
    stock: 200,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Luke', rating: 5, comment: 'Keeps my head incredibly warm.' }],
    averageRating: 5.0,
  },
  {
    title: 'Ray-Ban Classic Aviator Sunglasses',
    price: 161.00,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=750&fit=crop',
    description: 'The iconic aviator sunglasses originally designed for U.S. aviators in 1937. Features a gold frame and G-15 classic green lenses with 100% UV protection.',
    sizes: ['58mm'],
    colors: ['Gold/Green', 'Black/Grey'],
    stock: 45,
    featured: true,
    trending: false,
    reviews: [{ userName: 'Alex C.', rating: 5, comment: 'Genuine Ray-Bans, exactly as expected.' }],
    averageRating: 5.0,
  },
  {
    title: 'TRAVANDO Men\'s Slim Wallet with Money Clip',
    price: 29.95,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&h=750&fit=crop',
    description: 'Slim front pocket wallet designed to hold up to 11 cards. Features an integrated money clip and RFID blocking technology to protect your identity.',
    sizes: ['One Size'],
    colors: ['Carbon', 'Black', 'Cognac'],
    stock: 130,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Ian W.', rating: 4, comment: 'Very compact, takes some getting used to.' }],
    averageRating: 4.0,
  },
  
  // ===== ACTIVEWEAR =====
  {
    title: 'Nike Men\'s Dri-FIT Training Shorts',
    price: 30.00,
    category: 'Activewear',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=750&fit=crop',
    description: 'Lightweight and breathable training shorts featuring Dri-FIT technology to keep you dry and comfortable. Elastic waistband with interior drawcord.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Dark Grey', 'Navy'],
    stock: 90,
    featured: true,
    trending: true,
    reviews: [],
    averageRating: 0,
  },
  {
    title: 'adidas Men\'s Tiro 21 Track Pants',
    price: 45.00,
    originalPrice: 50.00,
    category: 'Activewear',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=750&fit=crop',
    description: 'Classic soccer-inspired track pants with a tapered fit. Made from moisture-absorbing AEROREADY fabric. Features ankle zips and side zip pockets.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black/White', 'Navy/White'],
    stock: 110,
    featured: false,
    trending: true,
    reviews: [{ userName: 'Tony', rating: 5, comment: 'The standard for track pants.' }],
    averageRating: 5.0,
  },

  // ===== OUTERWEAR =====
  {
    title: 'Columbia Men\'s Steens Mountain Full Zip Fleece Jacket',
    price: 39.99,
    originalPrice: 60.00,
    category: 'Outerwear',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop',
    description: 'Soft and warm full-zip fleece jacket perfect for cool days. Features a collared neck, zippered hand pockets, and a classic fit.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Charcoal Heather', 'Collegiate Navy'],
    stock: 85,
    featured: true,
    trending: true,
    reviews: [{ userName: 'John', rating: 4, comment: 'Great mid-layer for winter.' }],
    averageRating: 4.0,
  },
  {
    title: 'Levi\'s Men\'s Faux Leather Trucker Jacket',
    price: 79.99,
    originalPrice: 90.00,
    category: 'Outerwear',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop',
    description: 'Classic trucker jacket style in a durable faux leather finish. Features two chest flap pockets, two lower welt pockets, and adjustable snap cuffs.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Black', 'Dark Brown'],
    stock: 40,
    featured: false,
    trending: false,
    reviews: [],
    averageRating: 0,
  }
];

const seedProducts = async () => {
  try {
    console.log('⏳ Dropping existing products...');
    await Product.deleteMany({});
    console.log('⏳ Clearing all carts to prevent orphaned items...');
    await Cart.updateMany({}, { items: [] });
    
    console.log('⏳ Seeding new products...');
    await Product.insertMany(products);
    console.log(`✅ Successfully seeded ${products.length} products into the database!`);
  } catch (error) {
    console.error('❌ Error seeding products:', error.message);
  }
};

module.exports = seedProducts;
